import type { Product } from '../types/product';
import type { Category } from '../types/category';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Clothing',  slug: 'mens-clothing',   gender: 'men'   },
  { id: '2', name: 'Footwear',  slug: 'mens-footwear',   gender: 'men'   },
  { id: '3', name: 'Jewellery', slug: 'mens-jewellery',  gender: 'men'   },
  { id: '4', name: 'Clothing',  slug: 'womens-clothing',  gender: 'women' },
  { id: '5', name: 'Footwear',  slug: 'womens-footwear',  gender: 'women' },
  { id: '6', name: 'Jewellery', slug: 'womens-jewellery', gender: 'women' },
  { id: '7', name: 'Clothing',  slug: 'kids-clothing',  gender: 'kids' },
  { id: '8', name: 'Footwear',  slug: 'kids-footwear',  gender: 'kids' },
  { id: '9', name: 'Accessories', slug: 'kids-accessories', gender: 'kids' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'White Oversized Tee',
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    price: 1299,
    specifications: [
      { key: 'Material', value: '100% Cotton' },
      { key: 'Fit', value: 'Oversized' },
      { key: 'Occasion', value: 'Casual' },
      { key: 'Color', value: 'White' },
    ],
    description: 'Premium cotton oversized t-shirt perfect for everyday wear. Designed for comfort and style.',
    brand: 'H&M',
    stock: 50,
  },
  {
    id: '2',
    title: 'Classic White Sneakers',
    categoryId: '2',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80'],
    sizes: ['6', '7', '8', '9', '10'],
    price: 3999,
    specifications: [
      { key: 'Outer Material', value: 'Leather' },
      { key: 'Sole Material', value: 'Rubber' },
      { key: 'Occasion', value: 'Casual' },
      { key: 'Type', value: 'Sneakers' },
      { key: 'Color', value: 'White' },
    ],
    description: 'Minimalist leather sneakers that go with everything. Clean, classic, and comfortable.',
    brand: 'Nike',
    stock: 20,
  },
  {
    id: '3',
    title: 'Gold Chain Necklace',
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600&q=80'],
    sizes: [],
    price: 899,
    specifications: [
      { key: 'Color', value: 'Gold' },
      { key: 'Material', value: 'Gold Plated' },
      { key: 'Occasion', value: 'Casual, Formal' },
      { key: 'Type', value: 'Chain' },
    ],
    description: 'Minimalist gold chain perfect for layering or wearing solo. A timeless piece for any wardrobe.',
    brand: 'GIVA',
    stock: 30,
  },
  {
    id: '4',
    title: 'Black Slim Fit Jeans',
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    price: 2499,
    specifications: [
      { key: 'Material', value: 'Stretch Denim' },
      { key: 'Color', value: 'Black' },
      { key: 'Fit', value: 'Slim Fit' },
      { key: 'Occasion', value: 'Casual, Semi-formal' },
      { key: 'Wash Care', value: 'Machine wash cold, inside out' },
    ],
    description: 'Slim fit stretch denim in classic black. Sharp enough for a night out, comfortable enough for all day.',
    brand: 'H&M',
    stock: 35,
  },
  {
    id: '5',
    title: 'Floral Summer Dress',
    categoryId: '4',
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    price: 1699,
    specifications: [
      { key: 'Color', value: 'Multicolor' },
      { key: 'Material', value: 'Chiffon' },
      { key: 'Pattern', value: 'Floral' },
      { key: 'Occasion', value: 'Casual, Beach' },
      { key: 'Type', value: 'Midi Dress' },
      { key: 'Wash Care', value: 'Hand wash cold' },
    ],
    description: 'Light flowy chiffon dress with a beautiful floral print. Perfect for summer days and beach outings.',
    brand: 'H&M',
    stock: 25,
  },
  {
    id: '6',
    title: 'Block Heel Sandals',
    categoryId: '5',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80'],
    sizes: ['6', '7', '8', '9', '10'],
    price: 2299,
    specifications: [
      { key: 'Outer Material', value: 'Synthetic Leather' },
      { key: 'Color', value: 'Nude' },
      { key: 'Occasion', value: 'Casual, Work' },
      { key: 'Heel Height', value: '3 inches' },
      { key: 'Heel Type', value: 'Block Heel' },
      { key: 'Sole Material', value: 'TPR' },
    ],
    description: 'Comfortable block heel sandals that take you from desk to dinner. All day comfort without sacrificing style.',
    brand: 'Inc 5',
    stock: 0,
  },
  {
    id: '7',
    title: 'Pearl Drop Earrings',
    categoryId: '6',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80'],
    sizes: [],
    price: 599,
    specifications: [
      { key: 'Color', value: 'White' },
      { key: 'Material', value: 'Freshwater Pearl' },
      { key: 'Occasion', value: 'Casual, Formal, Wedding' },
      { key: 'Type', value: 'Drop Earrings' },
      { key: 'Pearl Type', value: 'Freshwater' },
      { key: 'Closure', value: 'Push Back' },
    ],
    description: 'Elegant freshwater pearl drop earrings set in sterling silver. A timeless classic for every occasion.',
    brand: 'GIVA',
    stock: 40,
  },
  {
    id: '8',
    title: 'Linen Blazer',
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    price: 4499,
    specifications: [
      { key: 'Material', value: 'Linen' },
      { key: 'Color', value: 'Beige' },
      { key: 'Fit', value: 'Regular Fit' },
      { key: 'Occasion', value: 'Smart Casual, Semi-formal' },
      { key: 'Wash Care', value: 'Dry clean only' },
    ],
    description: 'Smart casual linen blazer that elevates any outfit. Breathable fabric perfect for warm weather.',
    brand: 'XYZ',
    stock: 12,
  },
  {
    id: '9',
    title: 'Silk Midi Skirt',
    categoryId: '4',
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    price: 2199,
    specifications: [
      { key: 'Material', value: 'Silk' },
      { key: 'Color', value: 'Ivory' },
      { key: 'Length', value: 'Midi' },
      { key: 'Occasion', value: 'Casual, Formal' },
      { key: 'Wash Care', value: 'Dry clean only' },
    ],
    description: 'Elegant silk midi skirt with a fluid drape. Effortlessly transitions from day to evening.',
    brand: 'XYZ',
    stock: 20,
  },
  {
  id: '10',
  title: 'Kids Graphic Tee',
  categoryId: '7',
  images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600&q=80'],
  sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
  price: 699,
  specifications: [
    { key: 'Color', value: 'Blue' },
    { key: 'Material', value: '100% Cotton' },
    { key: 'Fit', value: 'Regular' },
    { key: 'Occasion', value: 'Casual' },
    { key: 'Wash Care', value: 'Machine wash cold' },
  ],
  description: 'Fun and comfortable graphic tee for kids. Soft cotton fabric perfect for everyday play.',
  brand: 'XYZ',
  stock: 40,
},
{
  id: '11',
  title: 'Kids White Sneakers',
  categoryId: '8',
  images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&q=80'],
  sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
  price: 1499,
  specifications: [
    { key: 'Outer Material', value: 'Synthetic' },
    { key: 'Occasion', value: 'Casual, School' },
    { key: 'Closure', value: 'Velcro' },
    { key: 'Color', value: 'White' },
    { key: 'Sole Material', value: 'Rubber' },
  ],
  
  description: 'Lightweight and durable sneakers for active kids. Easy velcro closure for independent wear.',
  brand: 'Puma',
  stock: 25,
},
{
  id: '12',
  title: 'Kids Cap',
  categoryId: '9',
  images: ['https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=600&q=80'],
  sizes: [],
  price: 399,
  specifications: [
    { key: 'Material', value: 'Cotton' },
    { key: 'Color', value: 'Red' },
    { key: 'Occasion', value: 'Casual, Outdoor' },
    { key: 'Type', value: 'Baseball Cap' },
    { key: 'Closure', value: 'Adjustable Snapback' },
  ],
  description: 'Cute and comfortable baseball cap for kids. Adjustable strap fits all head sizes.',
  brand: 'XYZ',
  stock: 60,
},
];